#pragma once

using namespace ATL;

template <class T>
class CProxy_ICPTracerFactoryEvents : public IConnectionPointImpl<T, &__uuidof( _ICPTracerFactoryEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
